name: Continous Integration workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: 'Run build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 'Checkout repository'
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: 'Install Dependencies'
        run: npm install
        
      - name: Run development server
        run: npm run dev
        
      - name: Build project
        run: npm run build
